import type { LibraryItem, SearchResponse } from "@/lib/types";

export const demoSearchResponse: SearchResponse = {
  search_id: "demo-search-01",
  query: "high-protein meal prep",
  timeframe: "7d",
  min_virality: 72,
  results: [
    {
      id: "clip_01",
      title: "3-second hook meal prep breakdown",
      platform: "tiktok",
      creator: "@studiobites",
      thumbnail_url: "https://images.unsplash.com/photo-1547592180-85f173990554?w=900",
      summary: "Fast-paced recipe proof, direct pay-off, and a visible transformation in under 20 seconds.",
      saved: false,
      content_dna: {
        id: 101,
        raw_clip_id: 201,
        schema_version: "v1",
        clip_id: "clip_01",
        source_url: "https://tiktok.com/@studiobites/video/123",
        platform: "tiktok",
        virality_score: 96,
        posted_at: "2026-03-28T14:22:00Z",
        niche: "fitness meal prep",
        hook: "This is the meal prep that finally stuck.",
        format: "quick-cut tutorial",
        emotion: "confidence",
        structure: "hook -> proof -> payoff -> call to action",
        cta: "Save this for Sunday prep",
        replication_notes: "Lead with the outcome, then reveal ingredients after the first beat.",
        pattern_tags: ["hook-proof", "quick-cut", "save-worthy"],
        confidence: 0.92,
      },
    },
    {
      id: "clip_02",
      title: "One pan lunches that sell the lifestyle",
      platform: "youtube_shorts",
      creator: "Kitchen Velocity",
      thumbnail_url: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=900",
      summary: "Clean voiceover, overhead shots, and a repeatable list structure that supports retention.",
      saved: true,
      content_dna: {
        id: 102,
        raw_clip_id: 202,
        schema_version: "v1",
        clip_id: "clip_02",
        source_url: "https://youtube.com/shorts/abc",
        platform: "youtube_shorts",
        virality_score: 91,
        posted_at: "2026-03-26T17:05:00Z",
        niche: "healthy cooking",
        hook: "Three lunches, one pan, zero stress.",
        format: "listicle",
        emotion: "relief",
        structure: "hook -> three examples -> recap -> CTA",
        cta: "Comment 'pan' and I’ll send the list",
        replication_notes: "Keep the first two seconds purely visual, then layer the list on top.",
        pattern_tags: ["listicle", "voiceover", "comment-cta"],
        confidence: 0.88,
      },
    },
    {
      id: "clip_03",
      title: "Budget grocery haul with a sharp turn",
      platform: "tiktok",
      creator: "@freshframe",
      thumbnail_url: "https://images.unsplash.com/photo-1550985543-f0a3e0c5f070?w=900",
      summary: "Narrative pivot from budget fear to confidence, with a strong before/after payoff.",
      saved: false,
      content_dna: {
        id: 103,
        raw_clip_id: 203,
        schema_version: "v1",
        clip_id: "clip_03",
        source_url: "https://tiktok.com/@freshframe/video/456",
        platform: "tiktok",
        virality_score: 84,
        posted_at: "2026-03-24T10:11:00Z",
        niche: "budget living",
        hook: "I thought this would be embarrassing.",
        format: "storytime",
        emotion: "surprise",
        structure: "confession -> constraint -> reveal -> takeaway",
        cta: "Follow for more realistic hauls",
        replication_notes: "Open with the emotional tension before showing any item.",
        pattern_tags: ["storytime", "before-after", "follow-cta"],
        confidence: 0.84,
      },
    },
  ],
  partial_failures: [],
  total_results: 3,
  generated_at: "2026-03-30T12:00:00Z",
};

export const demoLibraryItems: LibraryItem[] = [
  {
    id: "lib_01",
    content_dna_id: 101,
    saved_at: "2026-03-29T09:00:00Z",
    notes: "Use the hook structure in a transformation reel.",
    title: "3-second hook meal prep breakdown",
    creator: "@studiobites",
    thumbnail_url: "https://images.unsplash.com/photo-1547592180-85f173990554?w=900",
    platform: "tiktok",
    content_dna: demoSearchResponse.results[0].content_dna,
  },
  {
    id: "lib_02",
    content_dna_id: 102,
    saved_at: "2026-03-29T10:15:00Z",
    notes: "Good example of a list format with a clear CTA.",
    title: "One pan lunches that sell the lifestyle",
    creator: "Kitchen Velocity",
    thumbnail_url: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=900",
    platform: "youtube_shorts",
    content_dna: demoSearchResponse.results[1].content_dna,
  },
];
